### ISSUE TITLE
No avatar doesn't displayed with Black style

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#22] opened 2015-04-01 22:06 UTC
Hi,

with black style available here: https://www.phpbb.com/customise/db/style/black/ 

For this style, the "no avatar" images for users which doesn't have an avatar doesn't display in chat.

**Comment by LMOspaceace** [comment] 2015-04-01 22:29
this was due to the style black not using the phpbb default .gif image for the no avatar and the issue is fixed now with the included chat_body.html for black.

**Closed as completed by LMOspaceace** 2015-04-01 22:29 UTC
