### ISSUE TITLE
Simple user seen the delete button in chat

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#29] opened 2015-04-11 19:17 UTC
Hi,

on my board a simple user (user registered) seen the delete button in chat. See that: http://www.ezcom-fr.com/download/file.php?id=137

If he clicks on the delete button the message disappears, and if he refreshed the page the message re-appears.

No permission to moderate the chat was given to simple user.

**Comment by LMOspaceace** [comment] 2015-04-11 20:11
i'm unable to reproduce this issue. could you send me the login for an account that has that happening? you can pm it to me on phpbb.com as i'm in and out today

**Comment by Galixte** [comment] 2015-04-12 10:57
Hi @LMOspaceace,

Website: http://www.ezcom-fr.com

**Comment by LMOspaceace** [comment] 2015-04-12 11:54
i see no delete icon at all with that login. if you are testing a users permissions from an admin account, you will see the delete icon

**Comment by Galixte** [comment] 2015-04-12 13:09
OK, my test user has a permission to moderate in a particular forum (Standard Moderator permissions).

He sees the delete button of messages in ajax chat because in Standard Moderator permissions the next Ajax Chat permission is set on "Yes":`Can delete posts in chat`.

But he can't delete chat message when he click on delete button.

Only Global moderator and Admin can delete message, there is a bug.

**Comment by Reaper88** [comment] 2015-04-12 15:36
Then we have to modify our auth selection on that delete function, we'll look for which is best to achieve this.

**Comment by Galixte** [comment] 2015-04-12 18:21
Set to "No" or "Never" this permission does not change the fact that the user always sees the Delete button

**Comment by LMOspaceace** [comment] 2015-04-12 23:20
in the next version, there is a new permission role being added in favour of the current moderator permissions. no moderator will be able to delete messages until they get the role assigned to them by an admin. even global mods do not get the permission by default and has to be set

**Closed as completed** 2015-04-14 00:25 UTC
